POST http://localhost:9080/api/users/register HTTP/1.1
content-Type: application/json

{
  "sapId": "500108008",
  "name": "Sannidhya",
  "email": "sannidhya.108008@stu.upes.ac.in",
  "password": "s",
  "role": "Student",
  "username": "sannidhya108008"
}

###

POST http://localhost:9080/api/users/login HTTP/1.1
content-Type: application/json

{
  "email": "sannidhya.108008@stu.upes.ac.in",
  "password": "s"
}

###

POST http://localhost:9080/api/users/register HTTP/1.1
content-Type: application/json

{
  "sapId": "500108279",
  "name": "Ria",
  "email": "ria.108279@stu.upes.ac.in",
  "password": "s12345678",
  "role": "Student",
  "username": "ria108279"
}

###
POST http://localhost:9080/api/users/login HTTP/1.1
content-Type: application/json

{
  "email": "ria.108279@stu.upes.ac.in",
  "password": "s12345678"
}

###

POST http://localhost:9080/api/users/register HTTP/1.1
content-Type: application/json

{
  "sapId": "500106942",
  "name": "Mahika",
  "email": "mahika.106942@stu.upes.ac.in",
  "password": "m123456789",
  "role": "Student",
  "username": "mahika.6942"
}

###
POST http://localhost:9080/api/users/login HTTP/1.1
content-Type: application/json

{
    "email": "mahika.106942@stu.upes.ac.in",
    "password": "m123456789"
}


###
GET http://localhost:9080/api/users/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTdlNzY3MzEzZjQxOWI5ZDM5OTg4NiIsInNhcElkIjoiNTAwMTA4MDA4Iiwicm9sZSI6IlN0dWRlbnQiLCJpYXQiOjE3NDMyNTE2MjYsImV4cCI6MTc0Mzg1NjQyNn0.Zzjvy8hXZZE8oPEOON4ChonR1pjFAvq3X9CQ_DqQfLQ
Content-Type: application/json

###


POST http://localhost:9080/api/users/login HTTP/1.1
content-Type: application/json

{
  "email": "shubhanan.107856@stu.upes.ac.in",
  "password": "test1234"
}

###

GET  http://localhost:9080/api/users/allUsers HTTP/1.1
