POST http://localhost:9080/api/users/register HTTP/1.1
content-Type: application/json

{
  "sapId": "500108008",
  "name": "Sannidhya",
  "email": "sannidhya.108008@stu.upes.ac.in",
  "password": "s123456789",
  "role": "Student"
}

###

POST http://localhost:9080/api/users/login HTTP/1.1
content-Type: application/json

{
  "email": "sannidhya.108008@stu.upes.ac.in",
  "password": "s123456789"
}
